// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWJ92uF2MgwAyRJ6SIhgeVdiAExTW8El8',
    appId: '1:677204482473:web:f3a2511dc24a80dbbe0cb8',
    messagingSenderId: '677204482473',
    projectId: 'dofirst-63f27',
    authDomain: 'dofirst-63f27.firebaseapp.com',
    storageBucket: 'dofirst-63f27.firebasestorage.app',
    measurementId: 'G-24YCY177P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIoUQi7owCGCUIuQZOvEAr_J5f1SZrvGQ',
    appId: '1:677204482473:android:661e5898b4df69a9be0cb8',
    messagingSenderId: '677204482473',
    projectId: 'dofirst-63f27',
    storageBucket: 'dofirst-63f27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZyRqCW96ZFkVWyvEdZhs3FH8GTt_Ior8',
    appId: '1:677204482473:ios:643262ff5aa579b7be0cb8',
    messagingSenderId: '677204482473',
    projectId: 'dofirst-63f27',
    storageBucket: 'dofirst-63f27.firebasestorage.app',
    iosBundleId: 'com.example.dofirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZyRqCW96ZFkVWyvEdZhs3FH8GTt_Ior8',
    appId: '1:677204482473:ios:643262ff5aa579b7be0cb8',
    messagingSenderId: '677204482473',
    projectId: 'dofirst-63f27',
    storageBucket: 'dofirst-63f27.firebasestorage.app',
    iosBundleId: 'com.example.dofirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWJ92uF2MgwAyRJ6SIhgeVdiAExTW8El8',
    appId: '1:677204482473:web:096f7fcc35be3094be0cb8',
    messagingSenderId: '677204482473',
    projectId: 'dofirst-63f27',
    authDomain: 'dofirst-63f27.firebaseapp.com',
    storageBucket: 'dofirst-63f27.firebasestorage.app',
    measurementId: 'G-FWN8TC70B6',
  );
}
